Exception! (2018-01-14 16:51:04)
:::::::::::::::::::::::::::::::::::::::::::::::
Called from haxe.EntryPoint.run (C:\HaxeToolkit\haxe\std/haxe/EntryPoint.hx line 135)
Called from haxe.EntryPoint.processEvents (C:\HaxeToolkit\haxe\std/haxe/EntryPoint.hx line 106)
Called from haxe.MainLoop.tick (C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx line 156)
Called from haxe.Timer.new (C:\HaxeToolkit\haxe\std/haxe/Timer.hx line 74)
Called from client.KontentumClient.pingCallback (client/KontentumClient.hx line 202)
Called from client.KontentumClient.makeRequest (client/KontentumClient.hx line 217)
Called from haxe.Http.request (C:\HaxeToolkit\haxe\std/haxe/Http.hx line 387)

